apiVersion: v2
name: auth-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: redis
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - auth-redis

