apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-chart.fullname" . }}
  labels:
    {{- include "order-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "order-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web
      name: web
  type: {{ .Values.service.type }}
