apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ printf "%s/auth" .Values.authService.uri }}
    nginx.ingress.kubernetes.io/auth-response-headers: "X-UserId,X-User,X-First-Name,X-Last-Name,X-Email"
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /me
            backend:
              serviceName: {{ include "user-chart.fullname" . }}
              servicePort: {{ .Values.service.port }}
