apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  postgresql-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
