apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-chart.fullname" . }}
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "auth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "auth-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-nginx"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.imageNginx }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: web
          readinessProbe:
            httpGet:
              path: /health
              port: web
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
        - name: "{{ .Chart.Name }}-php-fpm"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.imagePhpFpm }}
          imagePullPolicy: {{ .Values.imageConfig.pullPolicy }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: REDIS_URI
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: USER_SERVICE_URI
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: php-fpm
          readinessProbe:
            tcpSocket:
              port: php-fpm
          resources:
            {{- toYaml .Values.phpFpm.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
