apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: app-skaffold
build:
  artifacts:
  - image: petr0vi4/app-nginx
    context: .
    docker:
      target: nginx
  - image: petr0vi4/app-php-fpm
    context: .
    docker:
      target: php-fpm
deploy:
  helm:
    releases:
      - name: app
        chartPath: ./app-chart
        artifactOverrides:
          imageNginx: petr0vi4/app-nginx
          imagePhpFpm: petr0vi4/app-php-fpm
