apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
data:
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  DATABASE_HOST: {{ .Values.postgresql.host | quote }}
  DATABASE_PORT: {{ .Values.postgresql.port | quote }}
  DATABASE_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: billing-secret
type: Opaque
data:
