{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "billing-chart.fullname" . }}
  labels:
    {{- include "billing-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "billing-chart.fullname" . }}
  namespaceSelector:
    matchNames:
    - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "billing-chart.selectorLabels" . | nindent 6  }}
  endpoints:
    - interval: 15s
      port: web
      path: /metrics/prometheus
{{- end }}
