apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  APP_SERVICE_URI: {{ .Values.appService.uri }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "pgsql://%s:%s@%s:%s/%s?charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  REDIS_URI: {{ printf "redis://%s@%s-master:%s/%s" .Values.redis.password (include "redis.fullname" .) .Values.redis.redisPort "0" | b64enc | quote }}