apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/petr0vi4/(auth|register|login|logout)
            backend:
              serviceName: {{ include "auth-chart.fullname" . }}
              servicePort: {{ .Values.service.port }}
