apiVersion: v2
name: postgresql
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: v1

dependencies:
  - name: postgresql
    version: 9.x.x
    repository: https://charts.bitnami.com/bitnami
